# Generated by Django 4.2.5 on 2023-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='slug',
        ),
        migrations.AddField(
            model_name='urldata',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
