# Generated by Django 4.2.5 on 2023-09-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_app', '0002_remove_urldata_slug_urldata_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='url_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
